// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190831150401_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infrastructure.Models.Player", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = "68ae6a34-6e23-4bdd-967c-2b7e27f67d08",
                            Level = 9,
                            Name = "Laz Ziya"
                        },
                        new
                        {
                            Id = "12338796-7482-4863-8ea2-9fb783bcf198",
                            Level = 3,
                            Name = "Ali"
                        },
                        new
                        {
                            Id = "2afc4226-021a-467e-8fcf-0f77117f3be5",
                            Level = 2,
                            Name = "Joe"
                        },
                        new
                        {
                            Id = "e9de70b2-7f4a-49f0-880e-611927b27a96",
                            Level = 0,
                            Name = "Jasmin"
                        },
                        new
                        {
                            Id = "80c41d65-5a38-44da-8ae7-ad396fa0439b",
                            Level = 2,
                            Name = "Michale"
                        },
                        new
                        {
                            Id = "630fc3ba-e984-4539-b54a-7a9789dae228",
                            Level = 8,
                            Name = "Lokman"
                        },
                        new
                        {
                            Id = "d4b45612-fbd4-44dd-a6d2-a7f6e92de8f9",
                            Level = 7,
                            Name = "Fantom"
                        },
                        new
                        {
                            Id = "a9257516-b5c0-496c-bbaa-6d3f3524a43e",
                            Level = 6,
                            Name = "DarkNight"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Treasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kind");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Treasures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kind = "Gold and diamond",
                            Name = "Crown",
                            Price = 999.0
                        },
                        new
                        {
                            Id = 2,
                            Kind = "Silver",
                            Name = "Sword",
                            Price = 700.0
                        },
                        new
                        {
                            Id = 3,
                            Kind = "Glass",
                            Name = "Lamp",
                            Price = 5.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
